(()=>{
const services={web:'Création web : sites vitrines, landing pages, plateformes web et interfaces responsive.',ecommerce:'E-commerce : boutiques, catalogues, fiches produits et parcours de commande.',social:'Réseaux sociaux : stratégie de contenu, optimisation de profils et développement d’audience.',ai:'Intelligence artificielle : assistants, automatisations, workflows et formation IA.',branding:'Branding & design : logo, identité visuelle, supports et direction créative.',ads:'Publicité digitale : stratégie, campagnes, ciblage et optimisation.',coaching:'Formation & coaching : entrepreneuriat, réseaux sociaux, IA et stratégie digitale.'};
const normalize=s=>s.toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'');
function local(q){const s=normalize(q);if(/bonjour|salut|hello|bonsoir/.test(s))return'Bonjour 👋 Je suis Bickri AI, l’assistant de Bickri Service Agency. Je peux vous renseigner sur nos services et vous orienter vers l’équipe.';if(/prix|tarif|cout|combien|devis/.test(s))return'Les tarifs sont personnalisés selon votre projet. Contactez Bickri Service Agency pour obtenir un devis.';if(/contact|whatsapp|email|numero/.test(s))return'WhatsApp : +227 88 37 61 33 — Email : bickriserviceagency@gmail.com.';for(const [k,v] of Object.entries(services))if(s.includes(k)||s.includes(normalize(v.split(':')[0])))return v+' Pour démarrer, utilisez le bouton « Démarrer ».';if(/service|proposez|offre/.test(s))return'Nous proposons : création web, e-commerce, réseaux sociaux, IA, branding & design, publicité digitale, formation et coaching.';return'Je peux vous renseigner sur nos services, nos accompagnements, les devis et la façon de démarrer un projet.'}
const st=document.createElement('style');st.textContent=`#bickriAiButton{position:fixed;right:22px;bottom:88px;z-index:80;width:62px;height:62px;border-radius:50%;border:1px solid #f3cf78;background:#08101f;color:#f3cf78;display:grid;place-items:center;font-weight:900;box-shadow:0 16px 40px #08101f44;cursor:pointer}#bickriAiPanel{position:fixed;right:22px;bottom:162px;z-index:79;width:min(390px,calc(100vw - 28px));height:min(620px,calc(100vh - 190px));display:none;flex-direction:column;overflow:hidden;border-radius:24px;background:#fff;border:1px solid #e3e8f0;box-shadow:0 28px 100px #08101f44}#bickriAiPanel.open{display:flex}.bai-head{padding:18px;background:linear-gradient(135deg,#08101f,#12203b);color:#fff;display:flex;justify-content:space-between}.bai-close{border:0;background:#ffffff18;color:#fff;border-radius:10px;width:34px;height:34px;font-size:18px}.bai-suggest{display:flex;gap:7px;overflow:auto;padding:10px;background:#fafbfd}.bai-chip{white-space:nowrap;border:1px solid #e1e6ee;background:#fff;border-radius:999px;padding:7px 10px;font-size:10px;font-weight:800}.bai-messages{flex:1;overflow:auto;padding:14px;background:#f7f9fc}.bai-msg{max-width:86%;margin:8px 0;padding:10px 12px;border-radius:15px;font-size:12px;line-height:1.55}.bai-msg.assistant{background:#fff;border:1px solid #e5eaf1}.bai-msg.user{margin-left:auto;background:#08101f;color:#fff}.bai-input{display:flex;gap:7px;padding:11px;border-top:1px solid #e5eaf1}.bai-input textarea{flex:1;resize:none;padding:10px;border:1px solid #dce3ed;border-radius:12px}.bai-send{width:45px;border:0;border-radius:12px;background:#d9a441;color:#08101f;font-size:17px}@media(max-width:620px){#bickriAiButton{right:14px;bottom:84px;width:57px;height:57px}#bickriAiPanel{right:10px;bottom:150px;width:calc(100vw - 20px)}}`;document.head.appendChild(st);
const panel=document.createElement('div');panel.id='bickriAiPanel';panel.innerHTML='<div class="bai-head"><div><strong>Bickri AI</strong><small style="display:block;color:#c4cedd">Assistant de Bickri Service Agency</small></div><button class="bai-close">×</button></div><div class="bai-suggest"><button class="bai-chip">Quels services proposez-vous ?</button><button class="bai-chip">Combien coûte un site ?</button><button class="bai-chip">Comment vous contacter ?</button></div><div class="bai-messages"></div><div class="bai-input"><textarea rows="1" placeholder="Posez votre question…"></textarea><button class="bai-send">➤</button></div>';document.body.appendChild(panel);
const btn=document.createElement('button');btn.id='bickriAiButton';btn.textContent='AI';document.body.appendChild(btn);const messages=panel.querySelector('.bai-messages'),input=panel.querySelector('textarea'),send=panel.querySelector('.bai-send');function add(text,role){const x=document.createElement('div');x.className='bai-msg '+role;x.textContent=text;messages.appendChild(x);messages.scrollTop=messages.scrollHeight}async function ask(){const q=input.value.trim();if(!q)return;add(q,'user');input.value='';let r='';try{const res=await fetch('/api/bickri-ai',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({message:q,history:[]})});if(res.ok){const d=await res.json();r=d.answer||''}}catch(e){}add(r||local(q),'assistant')}add('Bonjour 👋 Je suis Bickri AI. Comment puis-je vous renseigner ?','assistant');btn.onclick=()=>panel.classList.toggle('open');panel.querySelector('.bai-close').onclick=()=>panel.classList.remove('open');send.onclick=ask;input.onkeydown=e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();ask()}};panel.querySelectorAll('.bai-chip').forEach(c=>c.onclick=()=>{input.value=c.textContent;ask()});

// Conserver les personnes africaines sur les visuels existants.
const africanImageMap={
  'photo-1680878790148-18c83f270499':'photo-1680879275304-bbe20f7e28fb',
  'photo-1655720357761-f18ea9e5e7e6':'photo-1655720357872-ce227e4164ba',
  'photo-1611162617474-5b21e879e113':'photo-1655720357872-ce227e4164ba',
  'photo-1556761175-b413da4baf72':'photo-1655720357872-ce227e4164ba',
  'photo-1521737711867-e3b97375f902':'photo-1655720357872-ce227e4164ba'
};
function enforceAfricanImagery(){document.querySelectorAll('img').forEach(img=>{const src=img.getAttribute('src')||'';for(const [oldId,newId] of Object.entries(africanImageMap)){if(src.includes(oldId)){img.src=src.replace(oldId,newId);break}}})}
function adjustServiceCardImages(){
  const positions=['center 38%','center 34%','center 38%','center 28%','center 34%','center 34%','center 36%'];
  document.querySelectorAll('#serviceGrid .service').forEach((card,i)=>{const img=card.querySelector('.serviceImg');if(img){img.style.objectFit='cover';img.style.objectPosition=positions[i]||'center center';img.style.display='block'}})
}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>{enforceAfricanImagery();adjustServiceCardImages()});else{enforceAfricanImagery();adjustServiceCardImages()}
new MutationObserver(()=>{enforceAfricanImagery();adjustServiceCardImages()}).observe(document.body,{childList:true,subtree:true});
})();
