function json(res,status,body){return res.status(status).json(body);}
const SUPABASE_URL=()=>process.env.SUPABASE_URL||'https://okdohokhlkxrmxpevees.supabase.co';
const SUPABASE_KEY=()=>process.env.SUPABASE_SERVICE_ROLE_KEY;
const OPENAI_KEY=()=>process.env.OPENAI_API_KEY||process.env.AI_API_KEY;
const OPENAI_URL=()=>process.env.AI_API_URL||'https://api.openai.com/v1/responses';
const OPENAI_MODEL=()=>process.env.OPENAI_MODEL||process.env.AI_MODEL||'gpt-5.6-luna';
function session(req,res){const raw=String(req.headers.cookie||'');const m=raw.match(/(?:^|;\s*)bickri_legal_session=([a-zA-Z0-9_-]{16,100})/);if(m)return m[1];const id='legal_'+(typeof crypto!=='undefined'&&crypto.randomUUID?crypto.randomUUID().replace(/-/g,''):Date.now().toString(36)+Math.random().toString(36).slice(2));res.setHeader('Set-Cookie','bickri_legal_session='+id+'; Path=/; Max-Age=31536000; HttpOnly; Secure; SameSite=Lax');return id;}
function sbHeaders(){const k=SUPABASE_KEY();return {apikey:k,Authorization:'Bearer '+k,'Content-Type':'application/json',Accept:'application/json'};}
async function sb(path,opts={}){const k=SUPABASE_KEY();if(!k)throw new Error('SUPABASE_SERVICE_ROLE_KEY manquante');return fetch(SUPABASE_URL()+path,{...opts,headers:{...sbHeaders(),...(opts.headers||{})}});}
function chunks(text,size=6000){const out=[];for(let i=0;i<text.length;i+=size)out.push(text.slice(i,i+size));return out;}
function extractJson(text){try{return JSON.parse(text)}catch{}const a=String(text).indexOf('{'),b=String(text).lastIndexOf('}');if(a>=0&&b>a)try{return JSON.parse(text.slice(a,b+1))}catch{}return null;}
async function ai(instructions,input){const key=OPENAI_KEY();if(!key)return null;const r=await fetch(OPENAI_URL(),{method:'POST',headers:{'Content-Type':'application/json',Authorization:'Bearer '+key},body:JSON.stringify({model:OPENAI_MODEL(),instructions,input})});const d=await r.json().catch(()=>({}));if(!r.ok){console.error('Legal AI provider',r.status,d);return null}return typeof d.output_text==='string'?d.output_text.trim():Array.isArray(d.output)?d.output.flatMap(x=>Array.isArray(x.content)?x.content:[]).map(x=>x.text||'').filter(Boolean).join('\n').trim():null;}
const SYSTEM='Tu es Bickri Legal, assistant d’analyse documentaire juridique. Tu aides à comprendre, résumer, comparer et repérer des clauses. Tu fournis une analyse informative, pas un avis juridique ni une représentation d’avocat. Ne fabrique jamais un article de loi, une jurisprudence, une obligation ou une date. Si la juridiction ou la source manque, indique-le. Pour le droit nigérien, ne prétends pas vérifier le droit positif sans source fournie. Cite les extraits du document avec de courts passages et signale les incertitudes. Réponds en français, de manière claire et professionnelle.';
async function createDocument(sessionId,title,fileName,mime,text){const r=await sb('/rest/v1/legal_documents',{method:'POST',headers:{Prefer:'return=representation'},body:JSON.stringify({session_id:sessionId,title,file_name:fileName||null,mime_type:mime||null,source_text:text,status:'ready'})});const d=await r.json().catch(()=>[]);if(!r.ok)throw new Error(JSON.stringify(d));return d[0];}
async function saveChunks(documentId,text){const parts=chunks(text);for(let i=0;i<parts.length;i+=20){const batch=parts.slice(i,i+20).map((content,j)=>({document_id:documentId,chunk_index:i+j,content}));const r=await sb('/rest/v1/legal_chunks',{method:'POST',headers:{Prefer:'return=minimal'},body:JSON.stringify(batch)});if(!r.ok)console.error('chunk save',await r.text());}}
async function saveAnalysis(documentId,sessionId,type,result){await sb('/rest/v1/legal_analyses',{method:'POST',headers:{Prefer:'return=minimal'},body:JSON.stringify({document_id:documentId,session_id:sessionId,analysis_type:type,result,model:OPENAI_MODEL()})}).catch(()=>{});}
async function getDocument(id,sessionId){const r=await sb('/rest/v1/legal_documents?id=eq.'+encodeURIComponent(id)+'&session_id=eq.'+encodeURIComponent(sessionId)+'&select=id,title,file_name,document_type,source_text,created_at&limit=1');const d=await r.json().catch(()=>[]);return r.ok&&d[0]?d[0]:null;}
async function relevant(documentId,query){const q=String(query||'').trim().replace(/[^\p{L}\p{N}\s-]/gu,' ').slice(0,300);if(!q)return [];const r=await sb('/rest/v1/legal_chunks?document_id=eq.'+encodeURIComponent(documentId)+'&search_vector=fts.'+encodeURIComponent(q)+'&select=chunk_index,content&order=chunk_index.asc&limit=12');const d=await r.json().catch(()=>[]);return r.ok?d:[];}
module.exports=async function handler(req,res){
if(req.method==='OPTIONS'){res.setHeader('Access-Control-Allow-Origin','*');res.setHeader('Access-Control-Allow-Methods','POST,OPTIONS');res.setHeader('Access-Control-Allow-Headers','Content-Type');return res.status(204).end();}
if(req.method!=='POST')return json(res,405,{error:'Method not allowed'});
const sid=session(req,res),body=req.body||{},action=String(body.action||'').trim();
try{
if(action==='upload'){const text=typeof body.text==='string'?body.text.trim():'';if(!text)return json(res,400,{error:'Le texte du document est vide.'});if(text.length>160000)return json(res,400,{error:'Document trop volumineux. Limite: 160 000 caractères.'});const doc=await createDocument(sid,String(body.title||body.fileName||'Document juridique').slice(0,200),String(body.fileName||'').slice(0,200),String(body.mimeType||'').slice(0,100),text);await saveChunks(doc.id,text);return json(res,200,{document:{id:doc.id,title:doc.title,file_name:doc.file_name,characters:text.length}});}
if(action==='analyze'){const doc=await getDocument(String(body.documentId||''),sid);if(!doc)return json(res,404,{error:'Document introuvable.'});const jurisdiction=String(body.jurisdiction||'Non précisée').slice(0,100);const excerpt=doc.source_text.slice(0,100000);const prompt='Analyse ce document juridique.\nJuridiction: '+jurisdiction+'\nRetourne UNIQUEMENT un JSON valide avec les champs summary, document_type, parties, key_clauses, risks, missing_or_ambiguous et questions. key_clauses doit contenir title, excerpt, importance (high|medium|low). risks doit contenir title, severity (high|medium|low), explanation et recommendation. Ne déduis pas des faits absents.\nDOCUMENT:\n'+excerpt;const raw=await ai(SYSTEM,prompt);const result=extractJson(raw||'')||{summary:raw||'Analyse indisponible',key_clauses:[],risks:[],missing_or_ambiguous:[],questions:[]};await saveAnalysis(doc.id,sid,'full_review',result);if(result.summary)await sb('/rest/v1/legal_documents?id=eq.'+encodeURIComponent(doc.id),{method:'PATCH',headers:{Prefer:'return=minimal'},body:JSON.stringify({summary:String(result.summary).slice(0,12000)})});return json(res,200,{result,mode:raw?'ai':'fallback'});}
if(action==='ask'){const doc=await getDocument(String(body.documentId||''),sid);if(!doc)return json(res,404,{error:'Document introuvable.'});const question=String(body.question||'').trim();if(!question)return json(res,400,{error:'Question requise.'});const hits=await relevant(doc.id,question);const context=hits.length?hits.map(x=>'[Section '+(x.chunk_index+1)+'] '+x.content).join('\n\n'):doc.source_text.slice(0,30000);const answer=await ai(SYSTEM+' Réponds uniquement à partir du contexte documentaire. Si le contexte ne permet pas de répondre, dis-le clairement.', 'QUESTION: '+question+'\nCONTEXTE:\n'+context);const finalAnswer=answer||'Je ne peux pas analyser ce document pour le moment. Vérifiez que OPENAI_API_KEY est configurée dans Vercel.';await sb('/rest/v1/legal_messages',{method:'POST',headers:{Prefer:'return=minimal'},body:JSON.stringify({session_id:sid,document_id:doc.id,role:'user',content:question})}).catch(()=>{});await sb('/rest/v1/legal_messages',{method:'POST',headers:{Prefer:'return=minimal'},body:JSON.stringify({session_id:sid,document_id:doc.id,role:'assistant',content:finalAnswer})}).catch(()=>{});return json(res,200,{answer:finalAnswer,sources:hits.map(x=>({section:x.chunk_index+1,excerpt:x.content.slice(0,280)}))});}
if(action==='list'){const r=await sb('/rest/v1/legal_documents?session_id=eq.'+encodeURIComponent(sid)+'&select=id,title,file_name,document_type,summary,status,created_at&order=created_at.desc&limit=30');const d=await r.json().catch(()=>[]);return json(res,200,{documents:r.ok?d:[]});}
return json(res,400,{error:'Action inconnue.'});
}catch(e){console.error('Bickri Legal',e);return json(res,500,{error:'Erreur serveur. Vérifiez les variables Supabase/OpenAI et réessayez.'});}
};